language: go

# Only the last Go release are supported by the Go team with security
# updates. Any older versions be considered deprecated. Don't bother testing
# with them.
go:
  - 1.9.x

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
# install: true

# Don't email me the results of the test runs.
notifications:
  email: false


script:
  - go test -v  # Run all the tests